pipeline {
    agent any
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }
    
    stages {
      stage('SCM Checkout'){
          steps{
            git branch: 'main', url: 'https://github.com/zaaden77/Jenkins-CI.git' 
      }
    }
    stage ('Execute Ansible'){
        steps{
          ansiblePlaybook credentialsId: 'ansible-slave-key', disableHostKeyChecking: true, installation: 'ansible', inventory: "inventory/${params.inventory}", playbook: 'playbooks/site.yml'
        }
      }
    }
 }

