pipeline {
    agent any
    stages {
      stage('SCM Checkout'){
          steps{
            git branch: 'main', url: 'https://github.com/zaaden77/Jenkins-CI.git' 
      }
    }
    stage ('Execute Ansible'){
        steps{
          ansiblePlaybook credentialsId: 'ansible-slave-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
        }
      }
    }
 }

